apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: m3usick-prod

resources:
  - namespace.yaml
  - ../../base

images:
  - name: m3usick-web
    newName: 004908959120.dkr.ecr.ap-northeast-1.amazonaws.com/m3usick
    newTag: 2d9fd4b5faf39af6d903ede86f1e6707e41b6282
patches:
  - target:
      kind: Deployment
      name: m3usick-web
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/2/value
        value: production
      - op: replace
        path: /spec/template/spec/containers/0/env/4/value
        value: m3usick-auth-prod
      - op: replace
        path: /spec/template/spec/containers/0/env/8/value
        value: https://m3usick.com
  - target:
      kind: Ingress
      name: m3usick-web
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: m3usick.com
